import FWCore.ParameterSet.Config as cms

DTOfflineAnalyzer = cms.EDAnalyzer("DTOfflineAnalyzer",
    LCT_DT = cms.bool(True),                     
    recHits2DLabel = cms.string('dt2DSegments'), 
    rootFileName = cms.untracked.string('DTAnalyzerTest.root'),
    SALabel = cms.string('cosmicMuonsBarrelOnly'),         
    tTrigModeConfig = cms.untracked.PSet(
        vPropWire = cms.double(24.4),
        doTOFCorrection = cms.bool(False),
        ## tofCorrType = cms.int32(2),  ## old
        tofCorrType = cms.int32(0),
        kFactor = cms.double(-1.3),
        wirePropCorrType = cms.int32(0),
        doWirePropCorrection = cms.bool(False),
        tTrigLabel = cms.string(''),   ##For Collisions
        doT0Correction = cms.bool(True),
        debug = cms.untracked.bool(False)
    ),
    tTrigMode = cms.untracked.string('DTTTrigSyncFromDB'),
    doHits = cms.bool(True),
    PropagatorName = cms.string('SteppingHelixPropagator'),
    recHits4DLabel = cms.string('dt4DSegments'),
    doWheel0 = cms.bool(True),
    doWheel1 = cms.bool(True),
    doWheel2 = cms.bool(True),
    doWheelm2 = cms.bool(True),
    doWheelm1 = cms.bool(True),
    doTrig = cms.bool(True),
    doSegs = cms.bool(True),
    doSA = cms.bool(True),
    doTBox = cms.bool(False),
    doTBoxWhm2 = cms.bool(False),
    doTBoxWhm1 = cms.bool(False),
    doTBoxWh0 = cms.bool(False),
    doTBoxWh1 = cms.bool(False),
    doTBoxWh2 = cms.bool(False),
    doTBoxSector = cms.int32(0),
    doTBoxChamber= cms.int32(0),
    doTBoxSuperLayer= cms.int32(0),
    doTBoxLayer = cms.int32(0),
    isMC = cms.bool(True),
    #      bool isMC = false
    LCT_RPC = cms.bool(True),
    ###DTLocalTriggerLabel = cms.string('dtunpacker'),
    DTLocalTriggerLabel = cms.string('muonDTDigis'), ## RECO
    LCT_CSC = cms.bool(True),
    debug = cms.untracked.bool(False),
    recHits1DLabel = cms.string('dt1DRecHits')
)
